name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ secrets.DOCKER_USERNAME }}/pdf2stichwort:${{ github.ref_name }}
          cache-from: type=registry,ref=ghcr.io/${{ secrets.DOCKER_USERNAME }}/pdf2stichwort:latest
          cache-to: type=registry,ref=ghcr.io/${{ secrets.DOCKER_USERNAME }}/pdf2stichwort:latest,mode=max
